version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Containerfile
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app:z
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY:-ollama}
      - OPENAI_BASE_URL=${OPENAI_BASE_URL:-http://ollama:11434/v1}
    depends_on:
      - ollama
    networks:
      - agent-network
    restart: unless-stopped
    user: "1000:1000"  # Use a specific user ID for rootless mode

  frontend:
    build:
      context: ./frontend
      dockerfile: Containerfile
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app:z
      - frontend-node-modules:/app/node_modules:z
    environment:
      - NEXT_PUBLIC_API_BASE_URL=http://localhost:8000
      - NEXT_PUBLIC_WS_BASE_URL=ws://localhost:8000
    depends_on:
      - backend
    networks:
      - agent-network
    restart: unless-stopped
    user: "1000:1000"  # Use a specific user ID for rootless mode

  # Multiple Ollama services for true parallel processing
  ollama:
    image: ollama/ollama:latest
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama:Z
    networks:
      - agent-network
    restart: unless-stopped
    security_opt:
      - label=disable
    deploy:
      resources:
        limits:
          memory: 2G
        reservations:
          memory: 1G
    environment:
      - OLLAMA_NUM_PARALLEL=3
      - OLLAMA_MAX_LOADED_MODELS=1
      - OLLAMA_FLASH_ATTENTION=1

  ollama2:
    image: ollama/ollama:latest
    ports:
      - "11435:11434"
    volumes:
      - ollama_data2:/root/.ollama:Z
    networks:
      - agent-network
    restart: unless-stopped
    security_opt:
      - label=disable
    deploy:
      resources:
        limits:
          memory: 2G
        reservations:
          memory: 1G
    environment:
      - OLLAMA_NUM_PARALLEL=3
      - OLLAMA_MAX_LOADED_MODELS=1
      - OLLAMA_FLASH_ATTENTION=1

  ollama3:
    image: ollama/ollama:latest
    ports:
      - "11436:11434"
    volumes:
      - ollama_data3:/root/.ollama:Z
    networks:
      - agent-network
    restart: unless-stopped
    security_opt:
      - label=disable
    deploy:
      resources:
        limits:
          memory: 2G
        reservations:
          memory: 1G
    environment:
      - OLLAMA_NUM_PARALLEL=3
      - OLLAMA_MAX_LOADED_MODELS=1
      - OLLAMA_FLASH_ATTENTION=1

networks:
  agent-network:
    driver: bridge

volumes:
  ollama_data:
  ollama_data2:
  ollama_data3:
  frontend-node-modules:  # Separate volume for node_modules to avoid permission issues